### ISSUE TITLE
Побочная таска: добавить линтер в проект

### ISSUE THREAD

**Issue by Dasem** [w3st125/ATM#19]
Есть плагин линтера (что такое линтеры можешь почитать), например такой https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
Воткни его в свой проект и сделай чтоб он запускался при сборке проекта через мавен (на стадии compile, например)

**Comment by w3st125** [comment]
Сделать табуляцию 4 символа пробела (или табом, хз как по умолчанию)
Также если будут ещё какие-то странные требования линтера, тоже их поправить
+ не забыть сделать прогон плагина на стадии verify
